
// cocktails
export const INIT_LOADING = 'INIT_LOADING';
export const SEARCH_COCKTAILS = 'SEARCH_COCKTAILS';
export const FIRST_LETTER_COCKTAILS = 'FIRST_LETTER_COCKTAILS';
export const SHOW_ONE_COCKTAIL = 'SHOW_ONE_COCKTAIL';

// error cocktails
// export const ERROR_SEARCH_COCKTAILS = 'ERROR_SEARCH_COCKTAILS';
// export const ERROR_FIRST_LETTER_COCKTAILS = 'ERROR_FIRST_LETTER_COCKTAILS';
// export const ERROR_RESET_LOADING = 'ERROR_RESET_LOADING';
// export const ERROR_SHOW_ONE_COCKTAIL = 'ERROR_SHOW_ONE_COCKTAIL';